### ISSUE TITLE
all table elements that are a body id should include link to skeleton viewer

### ISSUE THREAD

**Issue by nneubarth** [connectome-neuprint/neuPrintExplorer#137]
create a body id display component that can be reused throughout the app

**Comment by nneubarth** [comment]
requires updating some query strings in neuprinthttp to return a hasSkeleton boolean

**Comment by neomorphic** [comment]
New neuprintHTTP endpoints no longer return hasSkeleton boolean, so just assume they all have one and update the plugins accordingly.

**Comment by neomorphic** [comment]
Fixed in connectome-neuprint/neuPrintExplorerPlugins@b5ed4a1c2016
