### ISSUE TITLE
number of rows per page reset when launching new tabs

### ISSUE THREAD

**Issue by nneubarth** [connectome-neuprint/neuPrintExplorer#141]
should remain static

**Comment by neomorphic** [comment]
@nneubarth, was there any mention about this being a global property or do they want it to be set on a per tab basis?

**Comment by nneubarth** [comment]
@neomorphic I believe they want it to be per tab. if a user is working in a tab and sets rows per page to X and then comes back to that tab they expect it to be as they left it regardless of what they did in other tabs

**Comment by neomorphic** [comment]
Of course, that is only 100x harder

**Comment by nneubarth** [comment]
All view state persisted for SimpleTable, CollapsibleTable, and PartnerCompletenessView except for sub-tables in the latter two, which handle their own state (IndependentTable.jsx). This feature can be added in future upon user request
