### ISSUE TITLE
multiple plugins fail to load due to incompatible query string handlers

### ISSUE THREAD

**Issue by nneubarth** [connectome-neuprint/neuPrintExplorer#151]
need to convert custom query, find similar neurons, roi connectivity, rois intersecting neurons, shortest path. should also update example plugin for documentation. We should consider writing better checks/tests to ensure mutual compatibility between neuPrintExplorer and plugins.

**Comment by neomorphic** [comment]
I fixed shortest path

**Comment by neomorphic** [comment]
Fixed rois intersecting neurons

**Comment by neomorphic** [comment]
Fixed FindSimilarNeurons

**Comment by neomorphic** [comment]
Fixed this with a bunch of commits
