### ISSUE TITLE
add information about datasets to home page

### ISSUE THREAD

**Issue by nneubarth** [connectome-neuprint/neuPrintExplorer#158]

**Comment by nneubarth** [comment]
Preliminary versions of markdown files available here:
* https://github.com/connectome-neuprint/neuPrint/blob/master/fib25_info.md
* https://github.com/connectome-neuprint/neuPrint/blob/master/mb6_info.md

**Comment by neomorphic** [comment]
Added links to home page in: a438be49e23b18
