### ISSUE TITLE
add ability to snapshot (bookmark) results

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#172]
Currently, users can add bookmarks for a given query.  But sometimes it is useful to see the actual results from an earlier query.  This issue requires that the actual data from the query is saved (along with a timestamp).  Some things will not be available, such as seeing the neuron shape in neuroglancer from a previous point in time.

**Comment by neomorphic** [comment]
This will require us to store that data in a database somewhere. I don't think we have a lot of options. localStorage would be one, but then they will only be able to access it from that browser on that device.

**Comment by stephenplaza** [comment]
Bookmarks are already stored in a google datastore

**Comment by neomorphic** [comment]
Completed in 90320a1f7cdd
