### ISSUE TITLE
Option to copy collected results 

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#177]
People often run a query just to put the results into another query. Add some way to take the format of a column as an input, like a built in collect function. Some check box where you can see and copy your results as  a, b, c, d or a,b,c,d.

**Comment by neomorphic** [comment]
Adding a "copy column to clipboard" icon would probably help cover this. Icon could show a pop up with options to copy as list, csv, or json.

**Comment by neomorphic** [comment]
Initial work was completed in 8f90acebf. Further enhancements can be done in the individual plugins and on a different issue ticket.
