### ISSUE TITLE
Find neurons color bar -- show ROI and % info

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#183]
Request from Tanya.  Please comment on the time to implement this request.

The current color graph on the far right of the find neurons plugin, requires users to hover over the bar to see the ROI and % ROI information.   At least for the bigger bars, provide an option to inline these values so that hovering is not necessary.

**Comment by neomorphic** [comment]
Fixed in 5408bff90af

**Comment by neomorphic** [comment]
Fixed in 5408bff90af
