### ISSUE TITLE
Remember scroll position for a tab (when switching between tabs)

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#184]
User request from Tanya.  Please provide an estimate when this can be completed.

For example, in Find neurons, you can get a long list of neurons that requires scrolling.  When a users scrolls and clicks on a neuron to view the skeleton, the scroll position is lost when returning to the original tab.  Can we remember this scroll position?

**Comment by neomorphic** [comment]
Fixed in 9287f8d09f4e24
