### ISSUE TITLE
Pop-up star plot for clicked neurons in find neurons

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#206]
Have the ability to see Marissa's new type or ROI visualization for a neuron in the find neurons plugin.  Perhaps show as a pop-up or put the visualization below the neuron id and make the row much taller.

**Comment by neomorphic** [comment]
See issue connectome-neuprint/neuPrintExplorerPlugins#37

**Comment by neomorphic** [comment]
[NeuPrint_Chart (1).pdf](https://github.com/connectome-neuprint/neuPrintExplorer/files/3772531/NeuPrint_Chart.1.pdf)
