### ISSUE TITLE
improve synapse visualization on skeletons

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#208]
* Add an option to show synapses in front of skeleton
* Increase the size of the synapse glyph relative to the body when zoomed out.

**Comment by hubbardp** [comment]
Pull request to support rendering synapses on top of neurons, like NeuTu:
https://github.com/connectome-neuprint/neuPrintExplorer/pull/225

**Comment by hubbardp** [comment]
The slider to control the synapse size has now been merged into the code:
https://github.com/connectome-neuprint/neuPrintExplorer/pull/243
