### ISSUE TITLE
improve front-page heatmap visualization

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#212]
Make the visualization more compact (just keep colors) and faster

Add pop-ups to give table cell information

clicking the cell should trigger a query to get neurons crossing the relevant ROIs

zoom in capability or expand button to see ROI labels?

**Comment by neomorphic** [comment]
All done apart from the zoom. I will leave that as a lower priority ticket and close this one.

See commits 3c3e3e02aeda1938d6ed38a7376068581397db4a to 10ace61f14c2362145bf0b1790b3d64ff2acd385
