### ISSUE TITLE
add menu grouping for different plugins

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#213]
We should change the UI to select plugins and make it look more like a menu.

The most important queries (find neurons, shortest path?, simple connectivity, custom) should be at the top. 

Category for viz: neuroglancer, skeleton, and cytoscape stuff

Category for reconstruction: completeness, distribution, partner completeness (we should remove autapse)

Maybe categories for neuron info (neurons in roi, etc) or connection info (ranked table, etc)

Miscellaneous category

**Comment by neomorphic** [comment]
Implemented in commits  ba29a93339  to 90e09080b0c
