### ISSUE TITLE
Close tabs error when no tabs are visible 

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#214]
When navigating out of the query results page with ~10+ results tabs open then back to a query, you cannot run another query and get the error "There are too many open tabs to submit another request. Please close some and submit again." The tabs have disappeared and there is no way to close out old results, so you lose all your results and have to refresh. 

![Screenshot from 2019-09-16 14-54-50](https://user-images.githubusercontent.com/51955732/64985486-f3e1d800-d892-11e9-8dc5-06468b721f8b.png)

**Comment by neomorphic** [comment]
Fixed in ba7310f1c56fa851
