### ISSUE TITLE
Blank page when not logged in

### ISSUE THREAD

**Issue by krokicki** [connectome-neuprint/neuPrintExplorer#232]
When navigating to neuPrint using a link from the Workstation (e.g. https://emdata1.int.janelia.org:11000/workstation?bodyid=327730878) you get to this page: 
![Screen Shot 2019-10-30 at 11 07 55 AM](https://user-images.githubusercontent.com/607324/67871039-1f004e00-fb06-11e9-9e06-2a4c9e84444a.png)
It would be nice if this asked you to log in, and then redirected you back to the page you wanted to view.

**Comment by neomorphic** [comment]
Fixed in 3498a8c05 & 3796c0b90. Will be deployed in the next release
