### ISSUE TITLE
improve speed and usability of synapse on skeleton selection

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#237]
Sometimes it is really slow to open up the synapse selection box for a given neuron.  Here are some strategies to speedup:

* limit the upstream/downstream connections to traced neurons or only show the top X
* don't download synapses until a user clicks on a given neuron

Usability issues:

* maybe allow user to collapse by cell type (don't show body id then)
* allow user to show all inputs and outputs as a single button
* show the cell type first and the body id in smaller font in parenthesis

**Comment by neomorphic** [comment]
Fixed in dbfbc8d6be1f6, f2b00c187f43f3, aeeadefafac4
