### ISSUE TITLE
search for neuron ids or types in the plugin before executing the query

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#240]
Some queries, like shortest paths, require users to type in specific body ids that are typically found by first running find neurons.  Other queries, like simple connection and ranked table, allow for wild card searches but they can often result in an unknown number of neurons being queried against the db which can be time consuming.

It would be good to have a mechanism, whether the query uses specific body ids or wild card or whatever, that first showed all the matching body ids, instances, and types.  Depending on the query type, the user could select to query all of them or just select certain cell types or body ids.

In some ways, this request is just a more stripped down 'Find Neurons' where 1) only a few columns are shown, 2) there is no ROI querying, and 3) the matching neuron table is meant to be a filter for another query and replace the view with the final result table.

It should be possible to view the matching neurons with only cell type or only instance names visible.  If this is done, the user should only see unique rows.

If the query only allows for cell type queries, cell types should be the only clickable words.  If the query allows for a list of body ids or cell types, the user could select an arbitrary number of different neurons (or click 'select all').

**Comment by neomorphic** [comment]
@stephenplaza how difficult would it be to add an end point to neuprintHTTP that returns the list of names/types/instances and their corresponding body ids when queried with a string?

**Comment by neomorphic** [comment]
The following cypher will return all body ids that contain the number 203. We could use this for autocompleting the search input when looking for a body id. There are probably other queries, additions to this query that would bring in results for type or instance.

MATCH (neuron :Neuron)
WHERE (neuron.bodyId+'') =~ '.*203.*'
RETURN neuron.bodyId AS bodyid
ORDER BY neuron.bodyId

**Comment by neomorphic** [comment]
`MATCH (neuron :`hemibrain_Neuron`)
WHERE (neuron.bodyId+'') =~ '.*SLP.*' OR neuron.type CONTAINS 'SLP' OR neuron.instance CONTAINS 'SLP'
RETURN neuron.bodyId AS bodyid, neuron.type AS type, neuron.instance AS instance
ORDER BY neuron.instance`

**Comment by neomorphic** [comment]
Change body id to exact match to speed up the query:

MATCH (neuron :`hemibrain-Neuron`)
WHERE neuron.bodyId = 295116205 OR neuron.type CONTAINS '295116205' OR neuron.instance CONTAINS '295116205'
RETURN neuron.bodyId AS bodyid, neuron.type AS type, neuron.instance AS instance
ORDER BY neuron.instance

**Comment by neomorphic** [comment]
This search interface has been implemented in connectome-neuprint/neuPrintExplorerPlugins@e5a8c07
