### ISSUE TITLE
ROI breakdown and sunburst graph disagree on input ROI percentages

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#241]
Body ID 549610772 has the ROI breakdown and sunburst graph of input shown below. The percentage of SMP input is shown in yellow in the ROI breakdown, and there is a clear discrepancy between the percentage of SMP input in the ROI breakdown vs. in the sunburst graph.  In addition, the sunburst graph shows the b'L as well as the MB(R/L) ROI, but the b'L is inside of the MB, so should not be displayed separately. 
<img width="1345" alt="smp2" src="https://user-images.githubusercontent.com/51955732/68783949-c652aa00-0609-11ea-9026-571631ee1b8d.PNG">

<img width="910" alt="smp" src="https://user-images.githubusercontent.com/51955732/68784251-45e07900-060a-11ea-98aa-b3360c2ff1cb.PNG">

**Comment by neomorphic** [comment]
Fixed in bb3af70ec590032
