### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#247]
* remove tab for slides
* replace data model picture with new one (ask Emily or Tom)
* add links to neuprint documentation in the first tab
* add a new tab called 'videos' that links to different tutorials

**Comment by stephenplaza** [comment]
change the tabs to have 1) ‘overview’ (which has the basic np explorer instructions and some followup information), 2) ‘analysis using explorer’ (will contain several tutorial videos and maybe basic biology terms), 3) ‘programmer’s interface’ (which will contain the http interface as well as other docs), 4) data modeling and batch analysis, 5) low-level technical details (neuprint paper, how to download, etc)

**Comment by neomorphic** [comment]
Updated in 290f9c077, 0e1d44a34, 40df69b5,  42cf6ec5e
