### ISSUE TITLE
simple connections '+' doesn't work with new data model

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#253]
Errors appear when clicking on the '+' in the simple connections result window.

**Comment by neomorphic** [comment]
@stephenplaza, that data is retrieved with the following cypher query, which is no longer returning a result:

```MATCH (n :`hemibrain_Segment` {bodyId: "2199257831"})-[x :ConnectsTo]->(b :`hemibrain_Segment` {bodyId: "2231988442"}) RETURN x.roiInfo```

is there roiInfo available on the new dataset? If not, the expansion panel may have to be removed.

**Comment by neomorphic** [comment]
Fixed in connectome-neuprint/neuPrintExplorerPlugins@df548a060c590
