### ISSUE TITLE
update front page to have 'neuron of the day'

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#254]
Replace the ROI completeness visualization (which could be made into a recon plugin), with a neuron of the day plugin fetched from the cached interface.

The cached interface will return skeleton coordinates and connectivity information for a sunburst plot.

The visualization will be the skeleton and sunburst plot with labels "neuron morphology" and "synapse connectivity (broken down by cell type and region)".  If needed, these visuals can be small icons of the interactive widgets ... clicking on them will give them an expanded pop-up window (maybe we need to do this for the ROI viewer as well?).

The label on the top should give the cell type name ("neuron of the day") which will be a link to a Find Neurons search for that cell type name.

**Comment by stephenplaza** [comment]
If we have "neuron morphology" and "synapse connectivity (broken down by cell type and region)" as captions for the new visuals, we should have "brain region connectivity" as a caption for the current visual.

**Comment by neomorphic** [comment]
You are calling this "neuron of the day", but you are asking to link to a cell type. Should we change it to "Cell Type of the day"?

**Comment by stephenplaza** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by neomorphic** [comment]
completed in commit a0461f67e3c
