### ISSUE TITLE
show full ROI name (on mouse over) for ROI abbreviations

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#257]
Where relevant in the UI, it would be good if there was some ability to get the full name of the ROI or description available, if the user hovers over the ROI abbreviation for awhile.

(The roi names and descriptions will need to be stored in the neuprint metadata)

**Comment by stephenplaza** [comment]
There should also be some general link at the top that will render the ROI hierarchy (as a pop-up).

**Comment by neomorphic** [comment]
> There should also be some general link at the top that will render the ROI hierarchy (as a pop-up).

What is the rational for doing this as a pop up? Will this hierarchy be in the documentation? Shouldn't we just link to that?

**Comment by neomorphic** [comment]
I take it the full names and descriptions are not currently stored in neuprint. Who do we need to assign that task?

**Comment by neomorphic** [comment]
Fixed in connectome-neuprint/neuPrintExplorerPlugins@7de25a3027, connectome-neuprint/neuPrintExplorerPlugins@11f08c3c52
