### ISSUE TITLE
Unable to load unsafe scripts in :13000

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#264]
Unable to use neuroglancer in :13000, not given the option to load unsafe scripts 

<img width="1385" alt="noshield" src="https://user-images.githubusercontent.com/51955732/71265263-d69a2b00-2313-11ea-9a90-6d623f449873.PNG">

**Comment by neomorphic** [comment]
Is this still an issue? The site shouldn't need to load unsafe scripts at this point.

**Comment by emjoyce** [comment]
no longer an issue
