### ISSUE TITLE
skeleton viewer: synapses not removed on removal of neuron

### ISSUE THREAD

**Issue by yangtansy** [connectome-neuprint/neuPrintExplorer#265]
In the skeleton viewer, once you have viewed the synapses of a skeleton and then removed that neuron skeleton and closed the skeleton viewer tab, the synapses will still appear even when you open a new skeleton viewer to view a different skeleton in the same neuPrint window. To remove the previous synapses from the skeleton viewer, a new NeuPrint window will need to be opened.

**Comment by emjoyce** [comment]
duplicate issue https://github.com/connectome-neuprint/neuPrintExplorer/issues/226

**Comment by neomorphic** [comment]
Fixed in commit 9c56c829097. Will be deployed with the next release of the site.
