### ISSUE TITLE
add syglass (VR) configuration download link

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#272]
In the skeleton viewer, please add a link that will download the following JSON that can be then imported into syGlass VR softwar.  Also, please only enable this download for ADMIN users for now.

{
"neuprint-token": "TOKEN",
"dvid-token": "TOKEN",
"dvid-addr": "ADRR/%d.ngmesh", # just a location for the ngmeshes
"neuprint-addr": "ADDR",
"dataset": "hemibrain:v1.0",
"bodies": [{"bodyid": ID1, "color": "#fff2a3", "type": "something"}, ...] # color is optional; future: specify pre and post annotation points
"rois": ["roi1", "roi2", ...]
}

**Comment by neomorphic** [comment]
@stephenplaza is the JSON format above the exact format that they are expecting? Also what exactly does "specify pre and post annotation points" mean?

**Comment by neomorphic** [comment]
Easily accessible information get us this:

`{
	"dataset": "hemibrain",
	"bodies": [
		"239736436",
		"708290604"
	],
	"rois": [
		"AB(L)",
		"AB(R)"
	]
}`

Types and colors will require additional engineering.

**Comment by neomorphic** [comment]
Mostly completed in f38a87a56 &  5e24b8a32c
