### ISSUE TITLE
ROI selection box and viz for skeleton viewer seems broken

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#273]
Can't deselect the last ROI

Sometimes an ROI is chosen and no mesh pops up.  When I check the network activity, I often see an OBJ being downloaded successfully just not displayed.

**Comment by neomorphic** [comment]
When no mesh pops up, this is likely because there is a bad value cached in the local data store. Clearing out the IndexedDB _pouch_neuprint_compartments should fix the issue.
