### ISSUE TITLE
Find neurons smart search type error

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#276]
The auto complete in the "Type" field list repeats of a the first matching type instead of possible type matches. e.g. typing in KC only returns:
KCa'b' - KCa'b'
KCa'b' - KCa'b'
KCa'b' - KCa'b'
KCa'b' - KCa'b'
...

In addition, the instance field is populated by the same instances, but different body IDs. e.g.
KC part due to gap - 12345
KC part due to gap - 45678
KC part due to gap- 67890
...

although this second point is not as much of a problem, it would probably be more helpful to have a list of different instances

**Comment by neomorphic** [comment]
This has been fixed in connectome-neuprint/neuPrintExplorerPlugins@ffbd642447
