### ISSUE TITLE
CSV download is not formatted properly

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuPrintExplorer#277]
(Disclaimer: I'm not sure if this is a problem with the frontend or with the backend.)

At least for the "completeness" page, the CSV download results in a file that looks like this:

```
Brain Region,%presyn,total presyn,%postsyn,total postsyn
AB(L), 91.54929577464789, 568, 59.79005998286204, 4668
AB(R), 98.43400447427292, 2682, 65.52321552321553, 20202
AL(L), 88.40900965319986, 167820, 58.9464994613186, 786179
AL(R), 91.3980406770314, 500479, 63.2651348036358, 2358653
```

The header row is delimited by a single comma, but the rest of the rows are delmited with comma-space (`, `).  This makes it inconvenient to parse in e.g. `pandas`. The extra spaces should be dropped.

**Comment by neomorphic** [comment]
Fixed in connectome-neuprint/neuPrintExplorerPlugins@9d97afa85c7
