### ISSUE TITLE
No apparent way to dismiss error messages

### ISSUE THREAD

**Issue by hubbardp** [connectome-neuprint/neuPrintExplorer#278]
I got some errors just now (perhaps due to working at home with a VPN?), producing that gray area at the bottom with error messages.  In the past, I have had a button for dismissing each line of the error messages (which is a bit tedious but workable).  With this one, though, I don't see any such way to get rid of the gray area.

<img width="1777" alt="Screen Shot 2020-01-13 at 11 16 14 AM" src="https://user-images.githubusercontent.com/32466564/72272376-8488b480-35f6-11ea-9a39-d0bfdce616e3.png">

**Comment by neomorphic** [comment]
Fixed in 45a71fdd985
