### ISSUE TITLE
Simple Connections - Searching for neurons shoudl return body ID and instance

### ISSUE THREAD

**Issue by emjoyce** [connectome-neuprint/neuPrintExplorer#280]
At the moment, when you search simple connections by a criteria that is true for multiuple neurons, you get a list of bodies that show the body ID twice. see the image for the issue:
<img width="887" alt="mbon" src="https://user-images.githubusercontent.com/51955732/72369920-1a900e00-36cf-11ea-8811-84d89ed83521.PNG">

In this example, user needs to be able to distinguish the right hemisphere MBON01 from the left, so having the instance on the display as well as the body ID would be very helpful. i.e.

MBON01(y5B'2a)(aSMPB)_L     id = (673509195)=>...

MBON01(y5B'2a)(aSMPB)_R     id = (612371421)=>...

**Comment by neomorphic** [comment]
Fixed in connectome-neuprint/neuPrintExplorerPlugins@65a79b11edb
