### ISSUE TITLE
Synapse connectivity summaries cut off in display

### ISSUE THREAD

**Issue by mmc46** [connectome-neuprint/neuPrintExplorer#285]
Both in Chrome and Firefox, it s showing up like this now
<img width="1467" alt="Screenshot 2020-06-01 at 10 56 23" src="https://user-images.githubusercontent.com/1872083/83398224-dcce2080-a3f6-11ea-9e6e-d65cf4e888e4.png">

**Comment by neomorphic** [comment]
You may need to clear your browser cache. have a look at this article. https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en
If that doesn't help, please let me know what versions of chrome and firefox you are using and on which OS.

**Comment by neomorphic** [comment]
The issue has been fixed in 95208905094b95f and will be deployed with our next release.
