### ISSUE TITLE
update neuprint+ documentation

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#297]
Add tagline to github, top of webpage if appropriate, and top of the documentation section:

"neuprint+: exploring inter and intra cellular interactions"

Replace neuprin+ data model based on the one posted in Slack.

Add a quick line to the top of the documentation and the top of the README that neuprint+ adds more capabilities for nesting sub-cellular structures and to refer to the diagram.  Also mention that additional plugin support to access this data has been provided.

**Comment by neomorphic** [comment]
Replace neuprin+ data model based on the one posted in Slack. -done

**Comment by neomorphic** [comment]
Added tag line in 659da9d9 & 476ca50fe79
Updated help page in dddeb78c4a3e
