### ISSUE TITLE
make objects returned in cell object plugin clickable

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#298]
A user should be able to click on the x,y,z of an object and then see all of that objects connections (MATCH (n :Element)-[x]-(m :Element) WHERE n.location = Point(blah) return x, m

This might be better to show as a pop-up rather than going to a new page ... I don't expect many connections.  But then again the elements that are connected to this Element could be clickable as well

**Comment by stephenplaza** [comment]
It might be good to show the 'parent' for the element.  If the user clicks on this parent and it is a cell, maybe you can redirect to a find neuron.  Alternatively, you can show the 'objects' for that parent.  

Workflow:

user shows mitos for a cell
user clicks on a mito and shows its relationships
user clicks on one of those elements
the user sees the parent cell for the clicked element, clicks on it, and then sees the objects for that cell

**Comment by neomorphic** [comment]
Clickable link was added in connectome-neuprint/neuPrintExplorerPlugins@18b53715c45f189
