### ISSUE TITLE
add spatial query

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorer#300]
let user find any elements close to a specified x,y,z ... return a list of xyz and element types.  these elements should be clickable

**Comment by neomorphic** [comment]
Query created in  connectome-neuprint/neuPrintExplorerPlugins@72ba5fdaed

**Comment by neomorphic** [comment]
fixed in connectome-neuprint/neuPrintExplorerPlugins@18b53715c45f189
