### ISSUE TITLE
Update to latest neuroglancer

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuPrintExplorer#306]
The latest version of neuroglancer includes features we'd like to use for our mitochondria data.

**Comment by tingzhao** [comment]
Note that updating to the latest neuroglancer will break the annotation function in neuprint. We may consider to switch the annotation layer to clio annotations.

**Comment by stuarteberg** [comment]
This is #306.  See #307.  :-)

**Comment by neomorphic** [comment]
Fixed in 392875d4e98e5ff7bf5d5f0f67788d4d32da61d0
