### ISSUE TITLE
Shortcut to reset skeleton orientation

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuPrintExplorer#309]
In last week's FlyEM project meeting, one [notable neuprint user][1] had a feature request for the neuprint skeleton viewer UI.  He explained that the viewer does not start out in any standard orientation.  Furthermore, when new neurons are added to the view, the orientation changes.

It would be nice if the viewer could be snapped back to some "standard" orientation via a keyboard shortcut.  Ideally, it would be an orientation that's relatively natural for biologists.  In the case of the hemibrain, I think the natural orientation would be to align with the XY plane (i.e. have the Z axis pointing away from the viewer).

[1]: https://www.janelia.org/people/gerry-rubin

cc @hubbardp

**Comment by stuarteberg** [comment]
It has been noticed (by the same notable neuprint user mentioned above) that the orientation chosen by the "reset view" button is a strange one.  Instead of having the X axis point to the right and the Y axis point down, the orientation is rotated 180° from where it should be.  Have a look at the screenshot below.  Notice the different orientations of the axis lines in neuroglancer vs. the skeleton view.  The default 3D orientation in neuroglancer is correct.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/1655821/205369225-335143cc-9d13-46d8-9c91-59ed95b646f8.png">


If we fix the default orientation, then it will match the view most people see when comparing to light images such as the one below.


![image](https://user-images.githubusercontent.com/1655821/205369847-89d812b0-35cc-4c4e-ae7a-e7f0f796ceca.png)

**Comment by neomorphic** [comment]
Default skeleton view has been flipped in 234f77c. This also flips the reset view button.
