### ISSUE TITLE
Data Error?

### ISSUE THREAD

**Issue by yiyin** [connectome-neuprint/neuPrintExplorer#311]
Hi,
I am not sure if this is the right place to submit issues about the potential data error, got directed from https://neuprint.janelia.org/about.

Basically, in Hemibrain v1.2, the neuron with bodyID 5812980863 (whose skeleton is completely within the LH) has two weird inputs in the AL from two AL local neurons (the orange dot in the AL). 
This is also verified on neuprint, with the two neurons (5813070873 and 5813018847) as inputs.

![image](https://user-images.githubusercontent.com/656268/126889341-51a225f0-5212-41d8-a168-24eff357a489.png)

**Comment by stuarteberg** [comment]
Thanks for reporting the problem.  We've now fixed it locally in our database.  When the data is eventually re-released as hemibrain v1.3, the fix will become public.
