### ISSUE TITLE
Augment "Find Similar Neurons" query page with option to use NBLAST scores

### ISSUE THREAD

**Issue by stuarteberg** [connectome-neuprint/neuPrintExplorer#328]
- [ ] Add a field in the neuprint `Meta` object to specify whether or not NBLAST scores are available in the neo4j database.
- [ ] Devise a suitable cypher query for neuprint explorer to construct
- [ ] Add an option to the UI for the user to select which algorithm to use (NBLAST vs. synapse distributions)

**Comment by umayaml** [comment]
Added `nBlastMatches` boolean to hemibrain_Meta. If `true` then `NblastMatchTo` relationship between Neurons exists in dataset.

**Comment by umayaml** [comment]
Example query to search for nblast matches for a bodyId with a score filter.
`MATCH(n :`hemibrain_Neuron`)-[x :NblastMatchTo]->(m :`hemibrain_Neuron`) WHERE x.score > 0.1 AND n.bodyId=1250920325 RETURN n.bodyId, n.instance, n.type, x.score, m.bodyId, m.instance, m.type ORDER By x.score DESC`

**Comment by neomorphic** [comment]
These updates were added to the @neuprint/queries module.
