### ISSUE TITLE
NeuroBridge link pointing to no results found

### ISSUE THREAD

**Issue by ghost** [connectome-neuprint/neuPrintExplorer#333]
Link found here does not point to Giant Fiber data no neurobrigde.
I'm not sure if Neurprint's link is bad or if NeuronBrigde has an issue

But Neuprint link shown in picture leads to no result found on NeuronBridge.

 #[](url)
![neuprint-link](https://user-images.githubusercontent.com/71096974/196726459-236ebf2b-0e0f-4591-b41f-2c126c368302.png)

![neuprint-neuonbridge-link](https://user-images.githubusercontent.com/71096974/196726487-69dff772-3bbc-4efc-ab21-432839edb6af.png)

**Comment by neomorphic** [comment]
The link has been restored and is working now
