### ISSUE TITLE
Colour panel doesn't disappear. 

### ISSUE THREAD

**Issue by YijieYin** [connectome-neuprint/neuPrintExplorer#345]
Hi, when I'm viewing the neurons in neuprint, if I want to change the colour of neurons, by clicking on the ids of the neurons, and then the colouring panels (called 'Change Color' when I hover on it), the panels don't disappear afterwards (shown in the screenshot below), even if I click elsewhere. 
![image](https://github.com/connectome-neuprint/neuPrintExplorer/assets/37304606/b2f3f2ed-289f-4d17-836f-50d75549bbf4)
[Here](https://neuprint.janelia.org/results?dataset=hemibrain%3Av1.2.1&qt=findneurons&q=1&qr%5B0%5D%5Bcode%5D=fn&qr%5B0%5D%5Bds%5D=hemibrain%3Av1.2.1&qr%5B0%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.2.1&qr%5B0%5D%5Bpm%5D%5Ball_segments%5D=false&qr%5B0%5D%5Bpm%5D%5Bfilters%5D%5Bpre%5D=&qr%5B0%5D%5Bpm%5D%5Bfilters%5D%5Bpost%5D=&qr%5B0%5D%5Bpm%5D%5Benable_contains%5D=true&qr%5B0%5D%5Bpm%5D%5Bneuron_name%5D=TuBu01&qr%5B0%5D%5BvisProps%5D%5BrowsPerPage%5D=25&qr%5B1%5D%5Bcode%5D=ng&qr%5B1%5D%5Bds%5D=hemibrain%3Av1.2.1&qr%5B1%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.2.1&qr%5B1%5D%5Bpm%5D%5Bskip%5D=true&qr%5B1%5D%5Bpm%5D%5BbodyIds%5D=1046726261%2C1047426385%2C1077459077%2C1077459090%2C1077459077&qr%5B2%5D%5Bcode%5D=sk&qr%5B2%5D%5Bds%5D=hemibrain%3Av1.2.1&qr%5B2%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.2.1&qr%5B2%5D%5Bpm%5D%5Bskip%5D=true&qr%5B2%5D%5Bpm%5D%5BbodyIds%5D=1046726261%2C1047426385%2C1077459077%2C1077459090%2C1077459077&tab=0&ftab=2)'s the link to the view if it helps. I haven't tried other datasets. Both my colleagues and I have this problem using different computers. We only tried using Mac. Please let me know if you need more information.

**Comment by neomorphic** [comment]
@YijieYin Those pop ups were set to close after pressing the [ESC] key. I have modified the code to allow clicking away to also close the pop ups. Thanks for reporting.

**Comment by YijieYin** [comment]
Hi, thanks for your response and for informing me of the [ESC] key. I just tried 'clicking away' but still have the same problem. FYI. But I can continue with using [ESC] from now.

**Comment by neomorphic** [comment]
@YijieYin , you will most likely have to refresh the cached version of the site. Go to this page: 

https://neuprint.janelia.org/about

If you don't see "Version: 1.61.10" under the neuPrintExplorer banner, then you will need to reload the site from the server.

**Comment by YijieYin** [comment]
Sorry, yes. I reloaded and it worked. Thank you!
