### ISSUE TITLE
Disable context menu when right clicking in Neuroglancer

### ISSUE THREAD

**Issue by hannahgooden** [connectome-neuprint/neuPrintExplorer#346]
When right clicking in Neuroglancer, the context menu appears. A workaround is to add `oncontextmenu="return false"` to the highest level Neuroglancer HTML tag (specifically, the tag with class `neuroglancer-container`) using the browser dev tools. Could this be incorporated into @janelia-flyem/neuroglancer?

![image](https://github.com/connectome-neuprint/neuPrintExplorer/assets/24723182/e7de14c0-2a9e-4ad9-ab5c-468b11331f61)

**Comment by neomorphic** [comment]
@hannahgooden , do you plan on using the @janelia-flyem/neuroglancer code elsewhere? If not, it is probably easier to add the context menu change to @janelia-flyem/react-neuroglancer.

**Comment by hannahgooden** [comment]
@janelia-flyem/react-neuroglancer would work too!

**Comment by hannahgooden** [comment]
Thank you so much!
