### ISSUE TITLE
Previous query results that were closed reappear upon launching a new query

### ISSUE THREAD

**Issue by nneubarth** [connectome-neuprint/neuPrintExplorer#86]
Produced when going from roi connectivity plugin to find neurons plugin

**Comment by nneubarth** [comment]
Prevents placeholder from appearing while waiting for query results. I assume that the placeholder is behind the existing query results.

**Comment by neomorphic** [comment]
This is a symptom of the plugins being rendered by two different systems. We need to migrate all the old plugins to get this behavior to go away.
